### PR TITLE
Scrutinizer fixes

### LINKED ISSUE #48: Fix Scrutinizer issues
https://scrutinizer-ci.com/g/deliciousbrains/wp-amazon-web-services/issues/develop

### PR DESCRIPTION
**Pull request by polevaultweb**
Resolves #48

### CODE REVIEW

**Comment by polevaultweb** [comment]
Ready for review again @ianmjones @bradt. then hopefully 0.2.1 is good to release when we do 0.8 AS3CF

File: classes/amazon-web-services.php [hunk 1]
```diff
@@ -122,11 +123,11 @@ function plugin_load() {
 	 * Process the saving of the settings form
 	 */
 	function handle_post_request() {
-		if ( empty( $_POST['action'] ) || 'save' != $_POST['action'] ) {
+		if ( empty( $_POST['action'] ) || 'save' != sanitize_key( $_POST['action'] ) ) { // input var okay
 			return;
 		}
 
-		if ( empty( $_POST['_wpnonce'] ) || ! wp_verify_nonce( $_POST['_wpnonce'], 'aws-save-settings' ) ) {
+		if ( empty( $_POST['_wpnonce'] ) || ! wp_verify_nonce( sanitize_key( $_POST['_wpnonce'] ), 'aws-save-settings' ) ) { // input var okay
```
Comment (bradt) [inline classes/amazon-web-services.php]: Why is it necessary to sanitize before passing into the `wp_verify_nonce()` function?
